### ISSUE TITLE
V3 Refactoring

### ISSUE THREAD

**Issue by jdbranham** [savantly-net/sprout-platform#134]
V3 will have many changes.  This is the main issue to track changes.   

Use the branch `v3.0` for this development.   https://github.com/savantly-net/sprout-platform/tree/v3.0
Please check code in frequently, as there are a lot of changes - so conflicts may be difficult to resolve.  

For the backend code, there are a few main items - 

- Removal of multi-tenancy, as it increases the development complexity, and most solutions will not require multi-tenancy.  
- Upgrading to latest Spring Boot, and replace Spring MVC with Spring WebFlux
- Temporarily remove DB Migrations.  

Tasks -  

- [ ] Removing the `tenancy` package from `sprout-core` (main and test) , and any compile issues in `sprout-core` that arise.   https://github.com/savantly-net/sprout-platform/issues/135
- [ ] Remove the multi-tenancy items in `sprout-spring-boot-starter`.  [main and test], and fix any compile issues that arise from the removal in `sprout-spring-boot-starter`.  https://github.com/savantly-net/sprout-platform/issues/136
- [ ] Upgrade Hibernate version. 
- [ ] Update entities that have Json Fields.  - see this for reference - https://stackoverflow.com/a/67467069/1308685 
- [ ] Disable the `flyway` DB migrations and enable the Spring Boot + Hibernate JPA automatic DDL creation.  
- [ ] Change the data integration tests to use H2 instead of Postgres.
- [ ] Ensure all tests pass in `sprout-spring-boot-starter` 
- [ ] Replace Spring Boot MVC with Spring WebFlux
- [ ] Refactor Spring Security - as the settings are different than Security with MVC
- [ ] Refactor Controllers/APIs to use Webflux instead of MVC
- [ ] Ensure all tests pass
